telemetry = false

[install]
# Only install package versions published at least 2 days ago (in seconds)
minimumReleaseAge = 172_800

# Don't install dependencies listed as "optional" by default
optional = false
